### ISSUE TITLE
"capture"spell 

### ISSUE THREAD

**Issue by krakkrak101** [Myuuiii/EmpireWandPlus#125]
the capture spell from the empire wand won't let you throw someone off your head after picking them up, the only way to drop them is by the second player shifting

**Comment by Myuuiii** [comment]
Thank you for reporting, I noticed this when testing last night. 
I will get started on this after work 😸

**Comment by Myuuiii** [comment]
@krakkrak101 I've written a fix for this, it's available [here](https://github.com/Myuuiii/EmpireWandPlus/releases/tag/beta-2.2.3-capture-spell-fix) for testing. Let me know if this is how you would desire it to be working :)

**Comment by krakkrak101** [comment]
it's great! thanks for the fix! :)

**Comment by Myuuiii** [comment]
I’m glad, the changes have been merged into the latest stable release!
