### ISSUE TITLE
Data.java

### ISSUE THREAD

**Issue by DronkenEend1** [Myuuiii/EmpireWandPlus#83]
Hey!

Dit is niet echt een issue, sorry.

Oke, ik ben nieuw met Java (en coding in general). Maar.. kan je niet gewoon bij Data.java alles final maken? Zelfde geldt voor WandSpellLists.java. Sorry als dit niet klopt, zoals ik al zei: ik ben nieuw met coden & Java! :D.

Je kan me evt. bereiken op Discord (DronkenEend#6651).

**Comment by Myuuiii** [comment]
Hoiii!!! Leuk dat je even wat achter laat! ik zou inderdaad alles final kunnen maken nu je het zegt! Ik voeg je ook wel even toe op Discord, dan zouden we evt nog even kunnen babbelen! ヾ(•ω•`)o

**Comment by Myuuiii** [comment]
> Hey!
> 
> Dit is niet echt een issue, sorry.
> 
> Oke, ik ben nieuw met Java (en coding in general). Maar.. kan je niet gewoon bij Data.java alles final maken? Zelfde geldt voor WandSpellLists.java. Sorry als dit niet klopt, zoals ik al zei: ik ben nieuw met coden & Java! :D.
> 
> Je kan me evt. bereiken op Discord (DronkenEend#6651).

Heyaa je hebt je friends list op private staan ^^; Als je wil mag je mij ook toevoegen, ik ben "Myuu#0001"

**Comment by DronkenEend1** [comment]
Hey! Ik zou je toevoegen. Sorry, ik weet niet eens waar ik die setting moet aanpassen! :D

**Comment by Myuuiii** [comment]
Er is btw 1 dingetje bij WandSpellLists.java waar deze lists worden overschreven als de gebruiker in de configuratie custom spells heeft opgegeven. Hier zou ik wel om heen kunnen werken. het zou het in ieder geval wel mooier maken denk ik.
